<a href="https://colab.research.google.com/github/anoop23822/anoop23822/blob/main/Air_Quality.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
import pandas as pd
import numpy as np
from google.colab import files

In [68]:
df = pd.read_csv("air_pollution_data.csv")

In [69]:
df.head()

,city,date,aqi,co,no,no2,o3,so2,pm2_5,pm10,nh3
0,Ahmedabad,30-11-2020,5,520.71,2.38,16.28,130.18,47.68,65.96,72.13,8.36
1,Ahmedabad,01-12-2020,5,1682.28,7.71,54.84,0.73,21.70,120.95,154.53,27.36
2,Ahmedabad,02-12-2020,5,1815.80,16.54,49.35,0.17,23.84,133.47,172.63,28.12
3,Ahmedabad,03-12-2020,5,2296.45,41.57,40.10,0.00,35.76,150.37,202.15,36.48
4,Ahmedabad,04-12-2020,5,2189.64,23.92,58.95,0.02,28.13,160.79,205.80,40.53

In [70]:
df.shape

(23504, 11)

In [71]:
df.isnull().sum()

city     0
date     0
aqi      0
co       0
no       0
no2      0
o3       0
so2      0
pm2_5    0
pm10     0
nh3      0
dtype: int64

In [72]:
df.duplicated().sum()

0

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23504 entries, 0 to 23503
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   city    23504 non-null  object
 1   date    23504 non-null  object
 2   aqi     23504 non-null  int64
 3   co      23504 non-null  float64
 4   no      23504 non-null  float64
 5   no2     23504 non-null  float64
 6   o3      23504 non-null  float64
 7   so2     23504 non-null  float64
 8   pm2_5   23504 non-null  float64
 9   pm10    23504 non-null  float64
 10  nh3     23504 non-null  float64
dtypes: float64(8), int64(1), object(2)
memory usage: 2.0+ MB

In [74]:
df.drop( columns = 'date', inplace = True)

In [75]:
df.head()

        city  aqi       co     no    no2      o3    so2   pm2_5    pm10    nh3
0  Ahmedabad    5   520.71   2.38  16.28  130.18  47.68   65.96   72.13   8.36
1  Ahmedabad    5  1682.28   7.71  54.84    0.73  21.70  120.95  154.53  27.36
2  Ahmedabad    5  1815.80  16.54  49.35    0.17  23.84  133.47  172.63  28.12
3  Ahmedabad    5  2296.45  41.57  40.10    0.00  35.76  150.37  202.15  36.48
4  Ahmedabad    5  2189.64  23.92  58.95    0.02  28.13  160.79  205.80  40.53

In [76]:

df1 = df.groupby('city').mean().reset_index()

In [77]:
df1

,city,aqi,co,no,no2,o3,so2,pm2_5,pm10,nh3
0,Ahmedabad,4.115044,1129.796969,10.324248,29.321327,27.862113,23.198717,81.831416,111.726482,16.245996
1,Aizawl,2.783186,356.212268,0.781914,7.289060,8.498518,1.946991,33.100442,38.440122,4.649757
2,Amaravati,3.702434,628.657588,0.486095,11.163927,40.595221,7.827887,66.601637,77.697235,5.428739
3,Amritsar,4.782080,1806.839204,5.136217,34.521427,32.966117,10.029867,176.562135,216.804779,37.476018
4,Bengaluru,2.856195,633.514967,3.804137,19.592854,39.032976,6.762312,31.514735,37.084237,3.533816
5,Bhopal,3.919248,717.600265,0.908551,13.597622,42.833186,7.114436,55.905265,71.593695,15.100166
6,Brajrajnagar,4.284292,646.729668,0.146139,14.022124,36.395199,9.322588,82.010642,93.713861,15.375940
7,Chandigarh,4.358407,866.393573,1.406150,24.436803,43.201482,6.863739,78.847345,104.325442,13.761438
8,Chennai,3.768805,1010.643075,7.070597,29.561460,35.608274,17.749923,65.357998,78.528451,6.426416
9,Coimbatore,2.799779,522.271626,0.459082,13.776792,36.323783,8.073175,31.675177,38.234480,3.997046
10,Delhi,4.808628,2300.481969,16.063794,47.273374,31.388927,30.680177,204.020664,282.070387,22.162920
11,Ernakulam,2.823009,440.259347,0.005133,10.222611,55.796184,5.934923,32.904170,39.816139,1.224646
12,Gurugram,4.682522,1844.882732,12.307478,49.401969,35.593097,16.020586,159.790387,198.342423,19.430111
13,Guwahati,4.096239,876.387611,3.982688,13.513761,17.909292,5.688252,64.247511,79.297810,9.858905
14,Hyderabad,3.809735,1378.375564,12.305940,33.485918,30.923595,20.416471,89.514524,104.581881,10.255210
15,Jaipur,4.336283,852.871748,0.956394,22.294314,50.731836,9.932942,74.388418,100.887400,17.877788
16,Jorapokhar,4.806416,1499.999723,12.702091,42.654314,23.544989,50.503485,141.835277,169.151217,10.451803
17,Kochi,2.823009,440.259347,0.005133,10.222611,55.796184,5.934923,32.904170,39.816139,1.224646
18,Kolkata,4.613938,3769.499690,49.846681,56.249392,12.043850,55.088717,337.177201,405.466272,24.100642
19,Lucknow,4.698009,1403.748794,1.904060,25.607434,41.394502,13.875122,154.789613,186.057124,20.699624
20,Mumbai,4.012168,1735.385564,4.651162,53.523119,33.661294,47.447113,144.756272,194.153496,18.224414
21,Patna,4.756637,1557.732367,2.570631,32.875586,37.903462,16.939148,177.857235,212.222511,16.533451
22,Shillong,3.384956,547.293153,0.089093,10.684071,41.079591,3.565254,41.855310,47.158861,5.588485
23,Talcher,4.037611,592.785741,0.071361,8.927124,34.884591,6.137887,83.155741,94.782732,6.722688
24,Thiruvananthapuram,3.195796,626.529524,4.853916,14.660962,16.070830,5.261759,39.627024,50.776549,3.117058
25,Visakhapatnam,3.674779,758.686029,3.305365,22.266737,49.515122,22.941283,81.325741,95.320631,4.097788

In [78]:
df1.shape

(26, 10)

In [80]:
file_path = '/bin/updated_data.csv'
df1.to_csv(file_path, index=False)
files.download(file_path)