<a href="https://colab.research.google.com/github/anoop23822/anoop23822/blob/main/imdb_movies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [17]:
df = pd.read_csv("/content/movies_metadata - movies_metadata.csv")
df.head(2)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,Unnamed: 24
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,373554033,81,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,FALSE,7.7,5415.0,NaN
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,262797249,104,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,FALSE,6.9,2413.0,NaN

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  50 non-null     bool
 1   belongs_to_collection  10 non-null     object
 2   budget                 50 non-null     int64
 3   genres                 50 non-null     object
 4   homepage               5 non-null      object
 5   id                     50 non-null     int64
 6   imdb_id                50 non-null     object
 7   original_language      50 non-null     object
 8   original_title         50 non-null     object
 9   overview               49 non-null     object
 10  popularity             50 non-null     object
 11  poster_path            50 non-null     object
 12  production_companies   50 non-null     object
 13  production_countries   50 non-null     object
 14  release_date           50 non-null     object
 15  revenue                50 non-null     object
 16  runtime                50 non-null     int64
 17  spoken_languages       50 non-null     object
 18  status                 50 non-null     object
 19  tagline                41 non-null     object
 20  title                  50 non-null     object
 21  video                  50 non-null     object
 22  vote_average           50 non-null     object
 23  vote_count             50 non-null     float64
 24  Unnamed: 24            1 non-null      float64
dtypes: bool(1), float64(2), int64(3), object(19)
memory usage: 9.5+ KB

In [21]:
third = df.iloc[2]['original_title']
print(third)

Grumpier Old Men

In [23]:
df.shape

(50, 25)

In [25]:
df[['title','genres']]

,title,genres
0,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '..."
1,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '..."
2,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ..."
3,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam..."
4,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]"
5,Heat,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam..."
6,Sabrina,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '..."
7,Tom and Huck,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam..."
8,Sudden Death,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam..."
9,GoldenEye,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '..."
10,The American President,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam..."
11,Dracula: Dead and Loving It,"[{'id': 35, 'name': 'Comedy'}, {'id': 27, 'nam..."
12,Balto,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '..."
13,Nixon,"[{'id': 36, 'name': 'History'}, {'id': 18, 'na..."
14,Cutthroat Island,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam..."
15,Casino,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name..."
16,Sense and Sensibility,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n..."
17,Four Rooms,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name..."
18,Ace Ventura: When Nature Calls,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name..."
19,Money Train,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam..."
20,Get Shorty,"[{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam..."
21,Copycat,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name..."
22,Assassins,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam..."
23,Powder,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name..."
24,Leaving Las Vegas,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n..."
25,Othello,"[{'id': 18, 'name': 'Drama'}]"
26,Now and Then,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam..."
27,Persuasion,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n..."
28,The City of Lost Children,"[{'id': 14, 'name': 'Fantasy'}, {'id': 878, 'n..."
29,In 1930's Shanghai violence was not the proble...,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name..."
30,Dangerous Minds,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name..."
31,Twelve Monkeys,"[{'id': 878, 'name': 'Science Fiction'}, {'id'..."
32,Wings of Courage,"[{'id': 10749, 'name': 'Romance'}, {'id': 12, ..."
33,Babe,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na..."
34,Carrington,"[{'id': 36, 'name': 'History'}, {'id': 18, 'na..."
35,Dead Man Walking,"[{'id': 18, 'name': 'Drama'}]"
36,Across the Sea of Time,"[{'id': 12, 'name': 'Adventure'}, {'id': 36, '..."
37,It Takes Two,"[{'id': 35, 'name': 'Comedy'}, {'id': 10751, '..."
38,Clueless,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam..."
39,"Cry, the Beloved Country","[{'id': 18, 'name': 'Drama'}]"
40,Richard III,"[{'id': 18, 'name': 'Drama'}, {'id': 10752, 'n..."
41,Dead Presidents,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam..."
42,Restoration,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n..."
43,Mortal Kombat,"[{'id': 28, 'name': 'Action'}, {'id': 14, 'nam..."
44,To Die For,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na..."
45,How To Make An American Quilt,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n..."
46,Se7en,"[{'id': 80, 'name': 'Crime'}, {'id': 9648, 'na..."
47,Pocahontas,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '..."
48,When Night Is Falling,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n..."
49,The Usual Suspects,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name..."

In [29]:
df[df['original_title']== 'Grumpier Old Men']

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,Unnamed: 24
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,0,101,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,FALSE,6.5,92.0,NaN

In [35]:
df = df.set_index('original_title')
result = df.loc['Grumpier Old Men']
print(result)

adult                                                                False
belongs_to_collection    {'id': 119050, 'name': 'Grumpy Old Men Collect...
budget                                                                   0
genres                   [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
homepage                                                               NaN
id                                                                   15602
imdb_id                                                          tt0113228
original_language                                                       en
overview                 A family wedding reignites the ancient feud be...
popularity                                                         11.7129
poster_path                               /6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg
production_companies     [{'name': 'Warner Bros.', 'id': 6194}, {'name'...
production_countries     [{'iso_3166_1': 'US', 'name': 'United States o...
release_date                                                    1995-12-22
revenue                                                                  0
runtime                                                                101
spoken_languages                  [{'iso_639_1': 'en', 'name': 'English'}]
status                                                            Released
tagline                  Still Yelling. Still Fighting. Still Ready for...
video                                                                FALSE
vote_average                                                           6.5
vote_count                                                            92.0
Unnamed: 24                                                            NaN
Name: Grumpier Old Men, dtype: object

In [42]:
df2 = df.sort_values('release_date', ascending=True)

In [43]:
df2

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,overview,popularity,...,release_date,revenue,runtime,spoken_languages,status,tagline,video,vote_average,vote_count,Unnamed: 24
original_title,,,,,,,,,,,,,,,,,,,,,
Father of the Bride Part II,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Just when George Banks has recovered from his ...,8.387519,...,1995-02-10,76578911,106,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,FALSE,5.7,173.0,NaN
When Night Is Falling,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,8391,tt0114916,en,"A prudish woman, working on tenure as a litera...",3.302524,...,1995-05-05,0,96,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,FALSE,5.9,10.0,NaN
La CitÃ© des Enfants Perdus,False,NaN,18000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 878, 'n...",NaN,902,tt0112682,fr,A scientist in a surrealist society kidnaps ch...,9.822423,...,1995-05-16,1738611,108,"[{'iso_639_1': 'cn', 'name': '??? / ???'}, {'i...",Released,Where happily ever after is just a dream.,FALSE,7.6,308.0,NaN
To Die For,False,NaN,20000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",NaN,577,tt0114681,en,Susan wants to work in television and will the...,10.448481,...,1995-05-20,21284514,106,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,All she wanted was a little attention.,FALSE,6.7,177.0,NaN
Pocahontas,False,"{'id': 136214, 'name': 'Pocahontas Collection'...",55000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",NaN,10530,tt0114148,en,History comes gloriously to life in Disney's e...,13.280069,...,1995-06-14,346079773,81,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,An American legend comes to life.,FALSE,6.7,1509.0,NaN
Babe,False,"{'id': 9435, 'name': 'Babe Collection', 'poste...",30000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",NaN,9598,tt0112431,en,Babe is a little pig who doesn't quite know hi...,14.404764,...,1995-07-18,254134910,89,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A little pig goes a long way.,FALSE,6,756.0,NaN
The Usual Suspects,False,NaN,6000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",http://www.mgm.com/#/our-titles/2083/The-Usual...,629,tt0114814,en,"Held in an L.A. interrogation room, Verbal Kin...",16.302466,...,1995-07-19,23341568,106,"[{'iso_639_1': 'es', 'name': 'EspaÃ±ol'}, {'iso...",Released,Five Criminals. One Line Up. No Coincidence.,FALSE,8.1,3334.0,NaN
Clueless,False,NaN,12000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,9603,tt0112697,en,"Shallow, rich and socially successful Cher is ...",9.882383,...,1995-07-19,0,97,"[{'iso_639_1': 'es', 'name': 'EspaÃ±ol'}, {'iso...",Released,Sex. Clothes. Popularity. Is there a problem h...,FALSE,6.9,828.0,NaN
Dangerous Minds,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",NaN,9909,tt0112792,en,Former Marine Louanne Johnson lands a gig teac...,9.481338,...,1995-08-11,180000000,99,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,She broke the rules... and changed their lives.,FALSE,6.4,249.0,NaN
Mortal Kombat,False,"{'id': 9818, 'name': 'Mortal Kombat Collection...",18000000,"[{'id': 28, 'name': 'Action'}, {'id': 14, 'nam...",NaN,9312,tt0113855,en,For nine generations an evil sorcerer has been...,10.870138,...,1995-08-18,122195920,101,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Nothing In This World Has Prepared You For This.,FALSE,5.4,452.0,NaN
Se7en,False,NaN,33000000,"[{'id': 80, 'name': 'Crime'}, {'id': 9648, 'na...",http://www.sevenmovie.com/,807,tt0114369,en,Two homicide detectives are on a desperate hun...,18.45743,...,1995-09-22,327311859,127,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Seven deadly sins. Seven ways to die.,FALSE,8.1,5915.0,NaN
Persuasion,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,17015,tt0114117,en,This film adaptation of Jane Austen's last nov...,2.228434,...,1995-09-27,0,104,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,FALSE,7.4,36.0,NaN
How To Make An American Quilt,False,NaN,10000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,11861,tt0113347,en,Soon-to-be-wed graduate student Finn Dodd deve...,4.485958,...,1995-10-06,23574130,116,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,There's beauty in the patterns of life.,FALSE,6.5,38.0,NaN
Dead Presidents,False,NaN,10000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,11443,tt0112819,en,"Depicts a heist of old bills, retired from cir...",9.87957,...,1995-10-06,0,119,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"In this daring heist, the only color that coun...",FALSE,6.6,80.0,NaN
Assassins,False,NaN,50000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,9691,tt0112401,en,Assassin Robert Rath arrives at a funeral to k...,11.065939,...,1995-10-06,30303072,132,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,"In the shadows of life, In the business of dea...",FALSE,6,394.0,NaN
Across the Sea of Time,False,NaN,0,"[{'id': 12, 'name': 'Adventure'}, {'id': 36, '...",NaN,139405,tt0112286,en,"A young Russian boy, Thomas Minton, travels to...",0.114469,...,1995-10-20,0,51,"[{'iso_639_1': 'ru', 'name': 'P??????'}, {'iso...",Released,NaN,FALSE,3.5,2.0,NaN
Now and Then,False,NaN,12000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,9263,tt0114011,en,Waxing nostalgic about the bittersweet passage...,8.681325,...,1995-10-20,27400000,100,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,In every woman there is the girl she left behind.,FALSE,6.6,91.0,NaN
Get Shorty,False,"{'id': 91698, 'name': 'Chili Palmer Collection...",30250000,"[{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...",NaN,8012,tt0113161,en,Chili Palmer is a Miami mobster who gets sent ...,12.669608,...,1995-10-20,115101622,105,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"The mob is tough, but itâ€™s nothing like show b...",FALSE,6.4,305.0,NaN
Powder,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",NaN,12665,tt0114168,en,Harassed by classmates who won't accept his sh...,12.133094,...,1995-10-27,0,111,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,An extraordinary encounter with another human ...,FALSE,6.3,143.0,NaN
Copycat,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",NaN,1710,tt0112722,en,An agoraphobic psychologist and a female detec...,10.701801,...,1995-10-27,0,124,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,One man is copying the most notorious killers ...,FALSE,6.5,199.0,NaN
Leaving Las Vegas,False,NaN,3600000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",http://www.mgm.com/title_title.do?title_star=L...,451,tt0113627,en,"Ben Sanderson, an alcoholic Hollywood screenwr...",10.332025,...,1995-10-27,49800000,112,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,I Love You... The Way You Are.,FALSE,7.1,365.0,NaN
Toy Story,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,...,1995-10-30,373554033,81,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,FALSE,7.7,5415.0,NaN
Carrington,False,NaN,0,"[{'id': 36, 'name': 'History'}, {'id': 18, 'na...",NaN,47018,tt0112637,en,The story of the relationship between painter ...,1.493361,...,1995-11-08,0,121,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A Love so Unusual it has to be True,FALSE,6.4,16.0,NaN
Ace Ventura: When Nature Calls,False,"{'id': 3167, 'name': 'Ace Ventura Collection',...",30000000,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",NaN,9273,tt0112281,en,"Summoned from an ashram in Tibet, Ace finds hi...",8.205448,...,1995-11-10,212385533,90,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,New animals. New adventures. Same hair.,FALSE,6.1,1128.0,NaN
GoldenEye,False,"{'id': 645, 'name': 'James Bond Collection', '...",58000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,en,James Bond must unmask the mysterious head of ...,14.686036,...,1995-11-16,352194034,130,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,No limits. No fears. No substitutes.,FALSE,6.6,1194.0,NaN
It Takes Two,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...",NaN,33689,tt0113442,en,Identical 9-year-olds from very different back...,7.777735,...,1995-11-17,0,101,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Two identical strangers. Two different worlds....,FALSE,6.1,149.0,NaN
The American President,False,NaN,62000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,9087,tt0112346,en,"Widowed U.S. president Andrew Shepherd, one of...",6.318445,...,1995-11-17,107879496,106,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Why can't the most powerful man in the world h...,FALSE,6.5,199.0,NaN
Money Train,False,NaN,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,11517,tt0113845,en,A vengeful New York transit cop decides to ste...,7.337906,...,1995-11-21,35431113,103,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Get on, or GET OUT THE WAY!",FALSE,5.4,224.0,NaN
Casino,False,NaN,52000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",NaN,524,tt0112641,en,The life of the gambling paradise â€“ Las Vegas ...,10.137389,...,1995-11-22,116112375,178,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,No one stays at the top forever.,FALSE,7.8,1343.0,NaN
Four Rooms,False,NaN,4000000,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",NaN,5,tt0113101,en,It's Ted the Bellhop's first night on the job....,9.026586,...,1995-12-09,4300000,98,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Twelve outrageous guests. Four scandalous requ...,FALSE,6.5,539.0,NaN
Sense and Sensibility,False,NaN,16500000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,4584,tt0114388,en,"Rich Mr. Dashwood dies, leaving his second wif...",10.673167,...,1995-12-13,135000000,136,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Lose your heart and come to your senses.,FALSE,7.2,364.0,NaN
"Cry, the Beloved Country",False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,34615,tt0112749,en,A South-African preacher goes to search for hi...,0.894647,...,1995-12-15,676525,106,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,FALSE,6.7,13.0,NaN
Jumanji,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,When siblings Judy and Peter discover an encha...,17.015539,...,1995-12-15,262797249,104,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,FALSE,6.9,2413.0,NaN
Othello,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,16420,tt0114057,en,The evil Iago pretends to be friend of Othello...,1.845899,...,1995-12-15,0,123,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Envy, greed, jealousy and love.",FALSE,7,33.0,NaN
Heat,False,NaN,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,949,tt0113277,en,"Obsessive master thief, Neil McCauley leads a ...",17.924927,...,1995-12-15,187436818,170,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,A Los Angeles Crime Saga,FALSE,7.7,1886.0,NaN
Sabrina,False,NaN,58000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,11860,tt0114319,en,An ugly duckling having undergone a remarkable...,6.677277,...,1995-12-15,0,127,"[{'iso_639_1': 'fr', 'name': 'FranÃ§ais'}, {'is...",Released,You are cordially invited to the most surprisi...,FALSE,6.2,141.0,NaN
Dracula: Dead and Loving It,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 27, 'nam...",NaN,12110,tt0112896,en,When a lawyer shows up at the vampire's doorst...,5.430331,...,1995-12-22,0,88,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,FALSE,5.7,210.0,NaN
Grumpier Old Men,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,A family wedding reignites the ancient feud be...,11.7129,...,1995-12-22,0,101,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,FALSE,6.5,92.0,NaN
Nixon,False,NaN,44000000,"[{'id': 36, 'name': 'History'}, {'id': 18, 'na...",NaN,10858,tt0113987,en,An all-star cast powers this epic look at Amer...,5.092,...,1995-12-22,13681765,192,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Triumphant in Victory, Bitter in Defeat. He Ch...",FALSE,7.1,72.0,NaN
Cutthroat Island,False,NaN,98000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,1408,tt0112760,en,"Morgan Adams and her slave, William Shaw, are ...",7.284477,...,1995-12-22,10017322,119,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The Course Has Been Set. There Is No Turning B...,FALSE,5.7,137.0,NaN
Sudden Death,False,NaN,35000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,9091,tt0114576,en,International action superstar Jean Claude Van...,5.23158,...,1995-12-22,64350171,106,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Terror goes into overtime.,FALSE,5.5,174.0,NaN
Balto,False,"{'id': 117693, 'name': 'Balto Collection', 'po...",0,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",NaN,21032,tt0112453,en,An outcast half-wolf risks his life to prevent...,12.140733,...,1995-12-22,11348324,78,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Part Dog. Part Wolf. All Hero.,FALSE,7.1,423.0,NaN
Waiting to Exhale,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,...,1995-12-22,81452156,127,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,FALSE,6.1,34.0,NaN
Tom and Huck,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,45325,tt0112302,en,"A mischievous young boy, Tom Sawyer, witnesses...",2.561161,...,1995-12-22,0,97,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The Original Bad Boys.,FALSE,5.4,45.0,NaN
Dead Man Walking,False,NaN,11000000,"[{'id': 18, 'name': 'Drama'}]",NaN,687,tt0112818,en,A justice drama based on a true story about a ...,6.891317,...,1995-12-29,39363635,122,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,FALSE,7.3,350.0,NaN
Richard III,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10752, 'n...",NaN,31174,tt0114279,en,Shakespeare's Play transplanted into a 1930s s...,4.561387,...,1995-12-29,0,104,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"I can smile, and murder while I smile",FALSE,6.9,50.0,NaN
Twelve Monkeys,False,NaN,29500000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",NaN,63,tt0114746,en,"In the year 2035, convict James Cole reluctant...",12.297305,...,1995-12-29,168840000,129,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The future is history.,FALSE,7.4,2470.0,NaN
Restoration,False,NaN,19000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,35196,tt0114272,en,"An aspiring young physician, Robert Merivel fo...",10.979269,...,1995-12-29,0,117,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,FALSE,6.3,30.0,NaN
"Guillaumet, les ailes du courage",False,NaN,0,"[{'id': 10749, 'name': 'Romance'}, {'id': 12, ...",NaN,78802,tt0114952,fr,NaN,0.745542,...,1996-09-18,0,50,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,FALSE,6.8,4.0,NaN
???,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",NaN,37557,tt0115012,zh,?????,A provincial boy related to a Shanghai crime f...,...,"[{'iso_3166_1': 'CN', 'name': 'China'}, {'iso_...",1995-04-30,0,108,"[{'iso_639_1': 'zh', 'name': '???'}]",Released,Shanghai Triad,FALSE,6.5,17.0